#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ride_Tracker_Database_Updater.DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="RideTracker")]
	public partial class ChapterClassDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertChapter(Chapter instance);
    partial void UpdateChapter(Chapter instance);
    partial void DeleteChapter(Chapter instance);
    #endregion
		
		public ChapterClassDataContext() : 
				base(global::Ride_Tracker_Database_Updater.Properties.Settings.Default.RideTrackerConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ChapterClassDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ChapterClassDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ChapterClassDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ChapterClassDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Chapter> Chapters
		{
			get
			{
				return this.GetTable<Chapter>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Chapters")]
	public partial class Chapter : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ChapterId;
		
		private string _ChapterName;
		
		private string _ChapterNickName;
		
		private System.Nullable<int> _ClubHouseAddressID;
		
		private System.Nullable<System.DateTime> _DateModified;
		
		private System.Nullable<System.DateTime> _DateCreated;
		
		private string _GoogleLink;
		
		private System.Nullable<bool> _Active;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnChapterIdChanging(int value);
    partial void OnChapterIdChanged();
    partial void OnChapterNameChanging(string value);
    partial void OnChapterNameChanged();
    partial void OnChapterNickNameChanging(string value);
    partial void OnChapterNickNameChanged();
    partial void OnClubHouseAddressIDChanging(System.Nullable<int> value);
    partial void OnClubHouseAddressIDChanged();
    partial void OnDateModifiedChanging(System.Nullable<System.DateTime> value);
    partial void OnDateModifiedChanged();
    partial void OnDateCreatedChanging(System.Nullable<System.DateTime> value);
    partial void OnDateCreatedChanged();
    partial void OnGoogleLinkChanging(string value);
    partial void OnGoogleLinkChanged();
    partial void OnActiveChanging(System.Nullable<bool> value);
    partial void OnActiveChanged();
    #endregion
		
		public Chapter()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChapterId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ChapterId
		{
			get
			{
				return this._ChapterId;
			}
			set
			{
				if ((this._ChapterId != value))
				{
					this.OnChapterIdChanging(value);
					this.SendPropertyChanging();
					this._ChapterId = value;
					this.SendPropertyChanged("ChapterId");
					this.OnChapterIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChapterName", DbType="VarChar(250)")]
		public string ChapterName
		{
			get
			{
				return this._ChapterName;
			}
			set
			{
				if ((this._ChapterName != value))
				{
					this.OnChapterNameChanging(value);
					this.SendPropertyChanging();
					this._ChapterName = value;
					this.SendPropertyChanged("ChapterName");
					this.OnChapterNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChapterNickName", DbType="VarChar(150)")]
		public string ChapterNickName
		{
			get
			{
				return this._ChapterNickName;
			}
			set
			{
				if ((this._ChapterNickName != value))
				{
					this.OnChapterNickNameChanging(value);
					this.SendPropertyChanging();
					this._ChapterNickName = value;
					this.SendPropertyChanged("ChapterNickName");
					this.OnChapterNickNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClubHouseAddressID", DbType="Int")]
		public System.Nullable<int> ClubHouseAddressID
		{
			get
			{
				return this._ClubHouseAddressID;
			}
			set
			{
				if ((this._ClubHouseAddressID != value))
				{
					this.OnClubHouseAddressIDChanging(value);
					this.SendPropertyChanging();
					this._ClubHouseAddressID = value;
					this.SendPropertyChanged("ClubHouseAddressID");
					this.OnClubHouseAddressIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateModified", DbType="Date")]
		public System.Nullable<System.DateTime> DateModified
		{
			get
			{
				return this._DateModified;
			}
			set
			{
				if ((this._DateModified != value))
				{
					this.OnDateModifiedChanging(value);
					this.SendPropertyChanging();
					this._DateModified = value;
					this.SendPropertyChanged("DateModified");
					this.OnDateModifiedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCreated", DbType="Date")]
		public System.Nullable<System.DateTime> DateCreated
		{
			get
			{
				return this._DateCreated;
			}
			set
			{
				if ((this._DateCreated != value))
				{
					this.OnDateCreatedChanging(value);
					this.SendPropertyChanging();
					this._DateCreated = value;
					this.SendPropertyChanged("DateCreated");
					this.OnDateCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GoogleLink", DbType="VarChar(MAX)")]
		public string GoogleLink
		{
			get
			{
				return this._GoogleLink;
			}
			set
			{
				if ((this._GoogleLink != value))
				{
					this.OnGoogleLinkChanging(value);
					this.SendPropertyChanging();
					this._GoogleLink = value;
					this.SendPropertyChanged("GoogleLink");
					this.OnGoogleLinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit")]
		public System.Nullable<bool> Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this.OnActiveChanging(value);
					this.SendPropertyChanging();
					this._Active = value;
					this.SendPropertyChanged("Active");
					this.OnActiveChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
